seems that the Debian Trixie riscv64 images are missing
Trying to pull docker.io/library/debian:trixie...
Error: choosing an image from manifest list docker://debian:trixie: no image found in manifest list for architecture riscv64, variant "", OS linux