Fix passing window xid to prop_set, prop_del.
Can be seen in mypy error:
xpra/x11/x11_server_core.py:206: error: Argument 1 to "prop_set" has incompatible type "Optional[Window]"; expected "int"

Transition to xid was started in commit 1994b30.

Causes this error at runtime:
2023-12-29 17:40:22,123 Error: <class 'TypeError'>, xid must be an int, not a <class 'gi.repository.GdkX11.X11Window'>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 170, in x11_init
    self.init_randr()
  File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 206, in init_randr
    prop_set(self.root_window, "_XPRA_RANDR_EXACT_SIZE", "u32", 1)
  File "/usr/lib/python3/dist-packages/xpra/x11/gtk_x11/prop.py", line 73, in prop_set
    raw_prop_set(xid, key, dtype, dformat, data)
  File "/usr/lib/python3/dist-packages/xpra/x11/gtk_x11/prop.py", line 77, in raw_prop_set
    raise TypeError(f"xid must be an int, not a {type(xid)}")
TypeError: xid must be an int, not a <class 'gi.repository.GdkX11.X11Window'>

GitHub issue #4087

Run tested on v5.0.4 (because my system can't run newer)